coverage:
  status:
    project: off
    patch: off

flag_management:
  individual_flags:
    - name: dna
      paths:
        - bin/dna
      statuses:
        - type: project
          target: 90%
          threshold: 1%
    - name: summing
        - bin/summing
      statuses:
        - type: project
          target: auto
          threshold: 1%